### ISSUE TITLE
Contact Details

### ISSUE THREAD

**Issue by gurjeetsinghvirdee** [deborahsv/About-Me#1]
Hey @deborahsv 

Don't add your contact details like phone number in your **Github**, if you adding it then switch it to private repository.
Hope you understand

**Comment by gurjeetsinghvirdee** [comment]
If you want to show your details like you added in this repo, you can make a special repo with your username deborahsv
watch this https://www.youtube.com/watch?v=SYtPC9tHYyQ

**Comment by deborahsv** [comment]
> Hey @deborahsv 
> 
> 
> 
> Don't add your contact details like phone number in your **Github**, if you adding it then switch it to private repository.
> 
> Hope you understand  

Thanks again, omg

**Comment by deborahsv** [comment]
> If you want to show your details like you added in this repo, you can make a special repo with your username deborahsv
> 
> watch this https://www.youtube.com/watch?v=SYtPC9tHYyQ
> 
> 

I'll watch, for now, i don't have so much to show, truth be told.

**Comment by gurjeetsinghvirdee** [comment]
Yeah it will take some time
just add some thing like badges your info what you know & most lang used or commits things
